# Generated by Django 3.2.16 on 2022-10-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=200)),
                ('max_tonn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonn_current', models.IntegerField(default=0)),
                ('nomer', models.CharField(max_length=20)),
                ('overload_percent', models.FloatField()),
                ('name_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.manufacturer')),
            ],
        ),
    ]
