# Generated by Django 3.2.16 on 2022-10-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name_manufacturer',
            new_name='manufacturer',
        ),
    ]
